[theme]
primaryColor = "#4361ee"
backgroundColor = "#f9fafb"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false